export const BUYER_LOGIN_POST= 'BUYER_LOGIN_POST';
export const BUYER_SIGNUP_POST= 'BUYER_SIGNUP_POST';
export const LOAD_BUYER_COOKIE= 'LOAD_BUYER_COOKIE';
export const OWNER_SIGNUP_POST= 'OWNER_SIGNUP_POST';
export const SECTION_POST= 'SECTION_POST';
export const ITEM_POST= 'ITEM_POST';
export const SEARCH_POST= 'SEARCH_POST';
